name: R-CI-Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: windows-latest
    timeout-minutes: 60

    env:
      R_LIBS_USER: ${{ github.workspace }}\\RLibrary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R 4.3.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\\RLibrary
          key: windows-r-4.3.3-lib-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            windows-r-4.3.3-lib-

      - name: Install R package tooling
        run: |
          Rscript -e "options(repos = c(CRAN = 'https://cran.rstudio.com')); install.packages(c('remotes','pkgload','testthat','covr','rcmdcheck'))"

      - name: Install package dependencies
        run: |
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Run unit tests (pkgload + testthat)
        run: |
          Rscript -e "library(pkgload); library(testthat);
                       pkgload::load_all(export_all = TRUE, helpers = TRUE);
                       testthat::test_dir('tests/testthat')"

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: --no-manual --as-cran

      - name: Upload check results (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-check-results
          path: check
